version: 2.1

orbs:
  architect: giantswarm/architect@0.11.0

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/flannel-network-health"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            tags:
              only: /^v.*/
